- name: Arabic
  code: ar
  native_name: العربية
- name: Bengali
  code: bn
  native_name: বাংলা
- name: Cantonese
  code: yue
  native_name: 廣東話
- name: Czech
  code: cs
  native_name: Čeština
- name: Danish
  code: da
  native_name: Dansk
- name: Dutch
  code: nl
  native_name: Nederlands
- name: English
  code: en
  native_name: English
- name: Finnish
  code: fi
  native_name: Suomi
- name: French
  code: fr
  native_name: Français
- name: German
  code: de
  native_name: Deutsch
- name: Greek
  code: el
  native_name: Ελληνικά
- name: Hebrew
  code: he
  native_name: עברית
- name: Hindi
  code: hi
  native_name: हिन्दी
- name: Hungarian
  code: hu
  native_name: Magyar
- name: Indonesian
  code: id
  native_name: Bahasa Indonesia
- name: Irish
  code: ga
  native_name: Gaeilge
- name: Italian
  code: it
  native_name: Italiano
- name: Japanese
  code: ja
  native_name: 日本語
- name: Korean
  code: ko
  native_name: 한국어
- name: Latin
  code: la
  native_name: Latina
- name: Mandarin Chinese
  code: zh
  native_name: 中文
- name: Norwegian
  code: "no"
  native_name: Norsk
- name: Persian
  code: fa
  native_name: فارسی
- name: Polish
  code: pl
  native_name: Polski
- name: Portuguese
  code: pt
  native_name: Português
- name: Romanian
  code: ro
  native_name: Română
- name: Russian
  code: ru
  native_name: Русский
- name: Scottish Gaelic
  code: gd
  native_name: Gàidhlig
- name: Spanish
  code: es
  native_name: Español
- name: Swahili
  code: sw
  native_name: Kiswahili
- name: Swedish
  code: sv
  native_name: Svenska
- name: Tagalog
  code: tl
  native_name: Tagalog
- name: Thai
  code: th
  native_name: ภาษาไทย
- name: Turkish
  code: tr
  native_name: Türkçe
- name: Ukrainian
  code: uk
  native_name: Українська
- name: Urdu
  code: ur
  native_name: اردو
- name: Vietnamese
  code: vi
  native_name: Tiếng Việt
- name: Welsh
  code: cy
  native_name: Cymraeg
